### ISSUE TITLE
remove the space in image name 

### ISSUE THREAD

**Issue by x0rld** [springcomp/wasd-iso-104-fr#2]
Hi,
You should remove the spaces in the image name cause if we send the link it does that 
![image](https://user-images.githubusercontent.com/45242856/81407782-46cb1100-913c-11ea-837f-5d2f2d5fc982.png)
so the link is not complete and we have a 404

**Comment by springcomp** [comment]
Thanks for the feedback. I will try.
In the meantime, replace the space with "%20" and you should be good to go 😉

**Comment by x0rld** [comment]
yeah that's what I did
